/*
 * wxJavaScript - main.cpp
 *
 * Copyright (c) 2002-2007 Franky Braem and the wxJavaScript project
 *
 * Project Info: http://www.wxjavascript.net or http://zzzJs.sourceforge.net
 *
 * This library is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2.1 of the License, or
 * (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301,
 * USA.
 *
 * $Id: main.cpp 810 2007-07-13 20:07:05Z fbraem $
 */
#include "precompile.h"


#ifdef _MSC_VER
	#pragma warning(disable:4800)
#endif 

#include <wx/wx.h>
#include <wx/language.h>


#ifdef __WXMSW__
	#include <windows.h>
#endif

#include "js/ext/jsmembuf.h"
#include "js/ext/point.h"
#include "js/ext/locale.h"
#include "js/ext/zzzjs_ext_init.h"

using namespace zzzJs;
using namespace zzzJs::ext;




JSConstDoubleSpec wxLanguageMap[] = 
{
	WXJS_CONSTANT(wxLANGUAGE_, DEFAULT)
	
	WXJS_CONSTANT(wxLANGUAGE_, UNKNOWN)
	WXJS_CONSTANT(wxLANGUAGE_, ABKHAZIAN)
	WXJS_CONSTANT(wxLANGUAGE_, AFAR)
	WXJS_CONSTANT(wxLANGUAGE_, AFRIKAANS)
	WXJS_CONSTANT(wxLANGUAGE_, ALBANIAN)
	WXJS_CONSTANT(wxLANGUAGE_, AMHARIC)
	WXJS_CONSTANT(wxLANGUAGE_, ARABIC)
	WXJS_CONSTANT(wxLANGUAGE_, ARABIC_ALGERIA)
	WXJS_CONSTANT(wxLANGUAGE_, ARABIC_BAHRAIN)
	WXJS_CONSTANT(wxLANGUAGE_, ARABIC_EGYPT)
	WXJS_CONSTANT(wxLANGUAGE_, ARABIC_IRAQ)
	WXJS_CONSTANT(wxLANGUAGE_, ARABIC_JORDAN)
	WXJS_CONSTANT(wxLANGUAGE_, ARABIC_KUWAIT)
	WXJS_CONSTANT(wxLANGUAGE_, ARABIC_LEBANON)
	WXJS_CONSTANT(wxLANGUAGE_, ARABIC_LIBYA)
	WXJS_CONSTANT(wxLANGUAGE_, ARABIC_MOROCCO)
	WXJS_CONSTANT(wxLANGUAGE_, ARABIC_OMAN)
	WXJS_CONSTANT(wxLANGUAGE_, ARABIC_QATAR)
	WXJS_CONSTANT(wxLANGUAGE_, ARABIC_SAUDI_ARABIA)
	WXJS_CONSTANT(wxLANGUAGE_, ARABIC_SUDAN)
	WXJS_CONSTANT(wxLANGUAGE_, ARABIC_SYRIA)
	WXJS_CONSTANT(wxLANGUAGE_, ARABIC_TUNISIA)
	WXJS_CONSTANT(wxLANGUAGE_, ARABIC_UAE)
	WXJS_CONSTANT(wxLANGUAGE_, ARABIC_YEMEN)
	WXJS_CONSTANT(wxLANGUAGE_, ARMENIAN)
	WXJS_CONSTANT(wxLANGUAGE_, ASSAMESE)
	WXJS_CONSTANT(wxLANGUAGE_, ASTURIAN)
	WXJS_CONSTANT(wxLANGUAGE_, AYMARA)
	WXJS_CONSTANT(wxLANGUAGE_, AZERI)
	WXJS_CONSTANT(wxLANGUAGE_, AZERI_CYRILLIC)
	WXJS_CONSTANT(wxLANGUAGE_, AZERI_LATIN)
	WXJS_CONSTANT(wxLANGUAGE_, BASHKIR)
	WXJS_CONSTANT(wxLANGUAGE_, BASQUE)
	WXJS_CONSTANT(wxLANGUAGE_, BELARUSIAN)
	WXJS_CONSTANT(wxLANGUAGE_, BENGALI)
	WXJS_CONSTANT(wxLANGUAGE_, BHUTANI)
	WXJS_CONSTANT(wxLANGUAGE_, BIHARI)
	WXJS_CONSTANT(wxLANGUAGE_, BISLAMA)
	WXJS_CONSTANT(wxLANGUAGE_, BOSNIAN)
	WXJS_CONSTANT(wxLANGUAGE_, BRETON)
	WXJS_CONSTANT(wxLANGUAGE_, BULGARIAN)
	WXJS_CONSTANT(wxLANGUAGE_, BURMESE)
	WXJS_CONSTANT(wxLANGUAGE_, CATALAN)
	WXJS_CONSTANT(wxLANGUAGE_, CHINESE)
	WXJS_CONSTANT(wxLANGUAGE_, CHINESE_SIMPLIFIED)
	WXJS_CONSTANT(wxLANGUAGE_, CHINESE_TRADITIONAL)
	WXJS_CONSTANT(wxLANGUAGE_, CHINESE_HONGKONG)
	WXJS_CONSTANT(wxLANGUAGE_, CHINESE_MACAU)
	WXJS_CONSTANT(wxLANGUAGE_, CHINESE_SINGAPORE)
	WXJS_CONSTANT(wxLANGUAGE_, CHINESE_TAIWAN)
	WXJS_CONSTANT(wxLANGUAGE_, CORSICAN)
	WXJS_CONSTANT(wxLANGUAGE_, CROATIAN)
	WXJS_CONSTANT(wxLANGUAGE_, CZECH)
	WXJS_CONSTANT(wxLANGUAGE_, DANISH)
	WXJS_CONSTANT(wxLANGUAGE_, DUTCH)
	WXJS_CONSTANT(wxLANGUAGE_, DUTCH_BELGIAN)
	WXJS_CONSTANT(wxLANGUAGE_, ENGLISH)
	WXJS_CONSTANT(wxLANGUAGE_, ENGLISH_UK)
	WXJS_CONSTANT(wxLANGUAGE_, ENGLISH_US)
	WXJS_CONSTANT(wxLANGUAGE_, ENGLISH_AUSTRALIA)
	WXJS_CONSTANT(wxLANGUAGE_, ENGLISH_BELIZE)
	WXJS_CONSTANT(wxLANGUAGE_, ENGLISH_BOTSWANA)
	WXJS_CONSTANT(wxLANGUAGE_, ENGLISH_CANADA)
	WXJS_CONSTANT(wxLANGUAGE_, ENGLISH_CARIBBEAN)
	WXJS_CONSTANT(wxLANGUAGE_, ENGLISH_DENMARK)
	WXJS_CONSTANT(wxLANGUAGE_, ENGLISH_EIRE)
	WXJS_CONSTANT(wxLANGUAGE_, ENGLISH_JAMAICA)
	WXJS_CONSTANT(wxLANGUAGE_, ENGLISH_NEW_ZEALAND)
	WXJS_CONSTANT(wxLANGUAGE_, ENGLISH_PHILIPPINES)
	WXJS_CONSTANT(wxLANGUAGE_, ENGLISH_SOUTH_AFRICA)
	WXJS_CONSTANT(wxLANGUAGE_, ENGLISH_TRINIDAD)
	WXJS_CONSTANT(wxLANGUAGE_, ENGLISH_ZIMBABWE)
	WXJS_CONSTANT(wxLANGUAGE_, ESPERANTO)
	WXJS_CONSTANT(wxLANGUAGE_, ESTONIAN)
	WXJS_CONSTANT(wxLANGUAGE_, FAEROESE)
	WXJS_CONSTANT(wxLANGUAGE_, FARSI)
	WXJS_CONSTANT(wxLANGUAGE_, FIJI)
	WXJS_CONSTANT(wxLANGUAGE_, FINNISH)
	WXJS_CONSTANT(wxLANGUAGE_, FRENCH)
	WXJS_CONSTANT(wxLANGUAGE_, FRENCH_BELGIAN)
	WXJS_CONSTANT(wxLANGUAGE_, FRENCH_CANADIAN)
	WXJS_CONSTANT(wxLANGUAGE_, FRENCH_LUXEMBOURG)
	WXJS_CONSTANT(wxLANGUAGE_, FRENCH_MONACO)
	WXJS_CONSTANT(wxLANGUAGE_, FRENCH_SWISS)
	WXJS_CONSTANT(wxLANGUAGE_, FRISIAN)
	WXJS_CONSTANT(wxLANGUAGE_, GALICIAN)
	WXJS_CONSTANT(wxLANGUAGE_, GEORGIAN)
	WXJS_CONSTANT(wxLANGUAGE_, GERMAN)
	WXJS_CONSTANT(wxLANGUAGE_, GERMAN_AUSTRIAN)
	WXJS_CONSTANT(wxLANGUAGE_, GERMAN_BELGIUM)
	WXJS_CONSTANT(wxLANGUAGE_, GERMAN_LIECHTENSTEIN)
	WXJS_CONSTANT(wxLANGUAGE_, GERMAN_LUXEMBOURG)
	WXJS_CONSTANT(wxLANGUAGE_, GERMAN_SWISS)
	WXJS_CONSTANT(wxLANGUAGE_, GREEK)
	WXJS_CONSTANT(wxLANGUAGE_, GREENLANDIC)
	WXJS_CONSTANT(wxLANGUAGE_, GUARANI)
	WXJS_CONSTANT(wxLANGUAGE_, GUJARATI)
	WXJS_CONSTANT(wxLANGUAGE_, HAUSA)
	WXJS_CONSTANT(wxLANGUAGE_, HEBREW)
	WXJS_CONSTANT(wxLANGUAGE_, HINDI)
	WXJS_CONSTANT(wxLANGUAGE_, HUNGARIAN)
	WXJS_CONSTANT(wxLANGUAGE_, ICELANDIC)
	WXJS_CONSTANT(wxLANGUAGE_, INDONESIAN)
	WXJS_CONSTANT(wxLANGUAGE_, INTERLINGUA)
	WXJS_CONSTANT(wxLANGUAGE_, INTERLINGUE)
	WXJS_CONSTANT(wxLANGUAGE_, INUKTITUT)
	WXJS_CONSTANT(wxLANGUAGE_, INUPIAK)
	WXJS_CONSTANT(wxLANGUAGE_, IRISH)
	WXJS_CONSTANT(wxLANGUAGE_, ITALIAN)
	WXJS_CONSTANT(wxLANGUAGE_, ITALIAN_SWISS)
	WXJS_CONSTANT(wxLANGUAGE_, JAPANESE)
	WXJS_CONSTANT(wxLANGUAGE_, JAVANESE)
	WXJS_CONSTANT(wxLANGUAGE_, KABYLE)
	WXJS_CONSTANT(wxLANGUAGE_, KANNADA)
	WXJS_CONSTANT(wxLANGUAGE_, KASHMIRI)
	WXJS_CONSTANT(wxLANGUAGE_, KASHMIRI_INDIA)
	WXJS_CONSTANT(wxLANGUAGE_, KAZAKH)
	WXJS_CONSTANT(wxLANGUAGE_, KERNEWEK)
	WXJS_CONSTANT(wxLANGUAGE_, KHMER)
	WXJS_CONSTANT(wxLANGUAGE_, KINYARWANDA)
	WXJS_CONSTANT(wxLANGUAGE_, KIRGHIZ)
	WXJS_CONSTANT(wxLANGUAGE_, KIRUNDI)
	WXJS_CONSTANT(wxLANGUAGE_, KONKANI)
	WXJS_CONSTANT(wxLANGUAGE_, KOREAN)
	WXJS_CONSTANT(wxLANGUAGE_, KURDISH)
	WXJS_CONSTANT(wxLANGUAGE_, LAOTHIAN)
	WXJS_CONSTANT(wxLANGUAGE_, LATIN)
	WXJS_CONSTANT(wxLANGUAGE_, LATVIAN)
	WXJS_CONSTANT(wxLANGUAGE_, LINGALA)
	WXJS_CONSTANT(wxLANGUAGE_, LITHUANIAN)
	WXJS_CONSTANT(wxLANGUAGE_, MACEDONIAN)
	WXJS_CONSTANT(wxLANGUAGE_, MALAGASY)
	WXJS_CONSTANT(wxLANGUAGE_, MALAY)
	WXJS_CONSTANT(wxLANGUAGE_, MALAYALAM)
	WXJS_CONSTANT(wxLANGUAGE_, MALAY_BRUNEI_DARUSSALAM)
	WXJS_CONSTANT(wxLANGUAGE_, MALAY_MALAYSIA)
	WXJS_CONSTANT(wxLANGUAGE_, MALTESE)
	WXJS_CONSTANT(wxLANGUAGE_, MANIPURI)
	WXJS_CONSTANT(wxLANGUAGE_, MAORI)
	WXJS_CONSTANT(wxLANGUAGE_, MARATHI)
	WXJS_CONSTANT(wxLANGUAGE_, MOLDAVIAN)
	WXJS_CONSTANT(wxLANGUAGE_, MONGOLIAN)
	WXJS_CONSTANT(wxLANGUAGE_, NAURU)
	WXJS_CONSTANT(wxLANGUAGE_, NEPALI)
	WXJS_CONSTANT(wxLANGUAGE_, NEPALI_INDIA)
	WXJS_CONSTANT(wxLANGUAGE_, NORWEGIAN_BOKMAL)
	WXJS_CONSTANT(wxLANGUAGE_, NORWEGIAN_NYNORSK)
	WXJS_CONSTANT(wxLANGUAGE_, OCCITAN)
	WXJS_CONSTANT(wxLANGUAGE_, ORIYA)
	WXJS_CONSTANT(wxLANGUAGE_, OROMO)
	WXJS_CONSTANT(wxLANGUAGE_, PASHTO)
	WXJS_CONSTANT(wxLANGUAGE_, POLISH)
	WXJS_CONSTANT(wxLANGUAGE_, PORTUGUESE)
	WXJS_CONSTANT(wxLANGUAGE_, PORTUGUESE_BRAZILIAN)
	WXJS_CONSTANT(wxLANGUAGE_, PUNJABI)
	WXJS_CONSTANT(wxLANGUAGE_, QUECHUA)
	WXJS_CONSTANT(wxLANGUAGE_, RHAETO_ROMANCE)
	WXJS_CONSTANT(wxLANGUAGE_, ROMANIAN)
	WXJS_CONSTANT(wxLANGUAGE_, RUSSIAN)
	WXJS_CONSTANT(wxLANGUAGE_, RUSSIAN_UKRAINE)
	WXJS_CONSTANT(wxLANGUAGE_, SAMI)
	WXJS_CONSTANT(wxLANGUAGE_, SAMOAN)
	WXJS_CONSTANT(wxLANGUAGE_, SANGHO)
	WXJS_CONSTANT(wxLANGUAGE_, SANSKRIT)
	WXJS_CONSTANT(wxLANGUAGE_, SCOTS_GAELIC)
	WXJS_CONSTANT(wxLANGUAGE_, SERBIAN)
	WXJS_CONSTANT(wxLANGUAGE_, SERBIAN_CYRILLIC)
	WXJS_CONSTANT(wxLANGUAGE_, SERBIAN_LATIN)
	WXJS_CONSTANT(wxLANGUAGE_, SERBO_CROATIAN)
	WXJS_CONSTANT(wxLANGUAGE_, SESOTHO)
	WXJS_CONSTANT(wxLANGUAGE_, SETSWANA)
	WXJS_CONSTANT(wxLANGUAGE_, SHONA)
	WXJS_CONSTANT(wxLANGUAGE_, SINDHI)
	WXJS_CONSTANT(wxLANGUAGE_, SINHALESE)
	WXJS_CONSTANT(wxLANGUAGE_, SISWATI)
	WXJS_CONSTANT(wxLANGUAGE_, SLOVAK)
	WXJS_CONSTANT(wxLANGUAGE_, SLOVENIAN)
	WXJS_CONSTANT(wxLANGUAGE_, SOMALI)
	WXJS_CONSTANT(wxLANGUAGE_, SPANISH)
	WXJS_CONSTANT(wxLANGUAGE_, SPANISH_ARGENTINA)
	WXJS_CONSTANT(wxLANGUAGE_, SPANISH_BOLIVIA)
	WXJS_CONSTANT(wxLANGUAGE_, SPANISH_CHILE)
	WXJS_CONSTANT(wxLANGUAGE_, SPANISH_COLOMBIA)
	WXJS_CONSTANT(wxLANGUAGE_, SPANISH_COSTA_RICA)
	WXJS_CONSTANT(wxLANGUAGE_, SPANISH_DOMINICAN_REPUBLIC)
	WXJS_CONSTANT(wxLANGUAGE_, SPANISH_ECUADOR)
	WXJS_CONSTANT(wxLANGUAGE_, SPANISH_EL_SALVADOR)
	WXJS_CONSTANT(wxLANGUAGE_, SPANISH_GUATEMALA)
	WXJS_CONSTANT(wxLANGUAGE_, SPANISH_HONDURAS)
	WXJS_CONSTANT(wxLANGUAGE_, SPANISH_MEXICAN)
	WXJS_CONSTANT(wxLANGUAGE_, SPANISH_MODERN)
	WXJS_CONSTANT(wxLANGUAGE_, SPANISH_NICARAGUA)
	WXJS_CONSTANT(wxLANGUAGE_, SPANISH_PANAMA)
	WXJS_CONSTANT(wxLANGUAGE_, SPANISH_PARAGUAY)
	WXJS_CONSTANT(wxLANGUAGE_, SPANISH_PERU)
	WXJS_CONSTANT(wxLANGUAGE_, SPANISH_PUERTO_RICO)
	WXJS_CONSTANT(wxLANGUAGE_, SPANISH_URUGUAY)
	WXJS_CONSTANT(wxLANGUAGE_, SPANISH_US)
	WXJS_CONSTANT(wxLANGUAGE_, SPANISH_VENEZUELA)
	WXJS_CONSTANT(wxLANGUAGE_, SUNDANESE)
	WXJS_CONSTANT(wxLANGUAGE_, SWAHILI)
	WXJS_CONSTANT(wxLANGUAGE_, SWEDISH)
	WXJS_CONSTANT(wxLANGUAGE_, SWEDISH_FINLAND)
	WXJS_CONSTANT(wxLANGUAGE_, TAGALOG)
	WXJS_CONSTANT(wxLANGUAGE_, TAJIK)
	WXJS_CONSTANT(wxLANGUAGE_, TAMIL)
	WXJS_CONSTANT(wxLANGUAGE_, TATAR)
	WXJS_CONSTANT(wxLANGUAGE_, TELUGU)
	WXJS_CONSTANT(wxLANGUAGE_, THAI)
	WXJS_CONSTANT(wxLANGUAGE_, TIBETAN)
	WXJS_CONSTANT(wxLANGUAGE_, TIGRINYA)
	WXJS_CONSTANT(wxLANGUAGE_, TONGA)
	WXJS_CONSTANT(wxLANGUAGE_, TSONGA)
	WXJS_CONSTANT(wxLANGUAGE_, TURKISH)
	WXJS_CONSTANT(wxLANGUAGE_, TURKMEN)
	WXJS_CONSTANT(wxLANGUAGE_, TWI)
	WXJS_CONSTANT(wxLANGUAGE_, UIGHUR)
	WXJS_CONSTANT(wxLANGUAGE_, UKRAINIAN)
	WXJS_CONSTANT(wxLANGUAGE_, URDU)
	WXJS_CONSTANT(wxLANGUAGE_, URDU_INDIA)
	WXJS_CONSTANT(wxLANGUAGE_, URDU_PAKISTAN)
	WXJS_CONSTANT(wxLANGUAGE_, UZBEK)
	WXJS_CONSTANT(wxLANGUAGE_, UZBEK_CYRILLIC)
	WXJS_CONSTANT(wxLANGUAGE_, UZBEK_LATIN)
	WXJS_CONSTANT(wxLANGUAGE_, VALENCIAN)
	WXJS_CONSTANT(wxLANGUAGE_, VIETNAMESE)
	WXJS_CONSTANT(wxLANGUAGE_, VOLAPUK)
	WXJS_CONSTANT(wxLANGUAGE_, WELSH)
	WXJS_CONSTANT(wxLANGUAGE_, WOLOF)
	WXJS_CONSTANT(wxLANGUAGE_, XHOSA)
	WXJS_CONSTANT(wxLANGUAGE_, YIDDISH)
	WXJS_CONSTANT(wxLANGUAGE_, YORUBA)
	WXJS_CONSTANT(wxLANGUAGE_, ZHUANG)
	WXJS_CONSTANT(wxLANGUAGE_, ZULU)
	WXJS_CONSTANT(wxLANGUAGE_, USER_DEFINED)
	WXJS_CONSTANT(wxLANGUAGE_, CAMBODIAN)
	{ 0 }
};



#ifdef __WXMSW__
	//BOOL WINAPI DllMain(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved)
	//{
	//	BOOL result = TRUE;
	//
	//	switch(fdwReason)
	//	{
	//	case DLL_PROCESS_ATTACH:
	//		DisableThreadLibraryCalls(hinstDLL);
	//		break;
	//	case DLL_PROCESS_DETACH:
	//		break;
	//	}    
	//
	//	return result;
	//}
#endif

WXJSAPI bool zzzJs::ext::InitClass(JSContext *cx, JSObject *global)
{
	MemoryBuffer::define_Class(cx, global);
    Point::define_Class(cx, global);
    Locale::define_Class(cx, global);

	// 
	{
		JSObject *constObj = JS_DefineObject(cx, global, "Language", 
    									   NULL, NULL,
										   JSPROP_READONLY | JSPROP_PERMANENT);
		JS_DefineConstDoubles(cx, constObj, wxLanguageMap);
	}
    return true;
}


/***
 * <file>globfun</file>
 * <module>ext</module>
 * <class name="Global Functions">
 *  On this page you can find all the functions/properties that are defined on the global object.
 * </class>
 * <properties>
 *  <property name="wxDefaultPosition" type="@wxPoint">
 *   The default position
 *  </property>
 * </properties>
 */
WXJSAPI bool zzzJs::ext::InitObject(JSContext *cx, JSObject *obj)
{
    Point::DefineObject(cx, obj, "wxDefaultPosition", new wxPoint(wxDefaultPosition));
    return true;
}

WXJSAPI void zzzJs::ext::Destroy()
{
}


WXJSAPI jsval zzzJs::ext::CreateMemoryBuffer(JSContext *cx, void *buffer, int size)
{
  wxMemoryBuffer *membuf = new wxMemoryBuffer(size);
  membuf->AppendData(buffer, size);
  JSObject *obj = JS_NewObject(cx, MemoryBuffer::GetClass(), NULL, NULL);
  if ( obj == NULL )
    return JSVAL_NULL;

  JS_SetPrivate(obj, membuf);
  return OBJECT_TO_JSVAL(obj);
}

WXJSAPI wxMemoryBuffer* zzzJs::ext::GetMemoryBuffer(JSContext *cx, JSObject *obj)
{
	return MemoryBuffer::GetPrivate(cx, obj);
}

WXJSAPI wxMemoryBuffer* zzzJs::ext::GetMemoryBuffer(JSContext *cx, jsval v)
{
  if ( v.isObject() /*JSVAL_IS_OBJECT(v)*/ )
  {
    return GetMemoryBuffer(cx, JSVAL_TO_OBJECT(v));
  }
  return NULL;
}

WXJSAPI wxMemoryBuffer* zzzJs::ext::NewMemoryBuffer(void *buffer, int size)
{
	wxMemoryBuffer *membuf = new wxMemoryBuffer(size);
	membuf->AppendData(buffer, size);
	return membuf;
}

WXJSAPI wxPoint* zzzJs::ext::GetPoint(JSContext *cx, JSObject *obj)
{
	return Point::GetPrivate(cx, obj);
}

WXJSAPI wxPoint* zzzJs::ext::GetPoint(JSContext *cx, jsval v)
{
  if ( v.isObject() /*JSVAL_IS_OBJECT(v)*/ )
  {
    return GetPoint(cx, JSVAL_TO_OBJECT(v));
  }
  return NULL;
}

WXJSAPI jsval zzzJs::ext::CreatePoint(JSContext *cx, const wxPoint &p)
{
  return Point::CreateObject(cx, new wxPoint(p));
}
