#include "precompile.h"


#ifdef _MSC_VER
	#pragma warning(disable:4800)
#endif 



#include "wx/wxprec.h"

#ifndef WX_PRECOMP
    #include "wx/wx.h"
#endif

#include "js/engine/mng_inst.h"
#include "js/common/conf.h"
#include "js/gui/event/jsevent.h"
#include "js/gui/event/spinevt.h"
#include "js/gui/event/notify.h"
#include "js/gui/misc/size.h"


using namespace zzzJs;
using namespace zzzJs::gui;

/***
 * <module>gui</module>
 * <file>event/spinevt</file>
 * <class name="wxSpinEvent" prototype="@wxNotifyEvent">
 *  This event class is used for the events generated by @wxSpinButton 
 *  and @wxSpinCtrl.
 * </class>
 */
WXJS_INIT_CLASS(SpinEvent, "SpinEvent", 0)

/***
 * <properties>
 *  <property name="position" type=WXJS_TYPE_NUMBER>
 *   Get/Set the current spin button or control value.
 *  </property>
 * </properties>
 */
WXJS_BEGIN_PROPERTY_MAP(SpinEvent)
	WXJS_PROPERTY(P_POSITION, "position")
WXJS_END_PROPERTY_MAP()

bool SpinEvent::GetProperty(PrivSpinEvent *p,
                                  JSContext *cx, 
                                  JSObject *obj, 
                                  int id, 
                                  JS::MutableHandle<JS::Value>& vp)
{
	wxSpinEvent *event = (wxSpinEvent*) p->GetEvent();

	switch ( id )
	{
	case P_POSITION:
		ToJSVal(cx, vp, event->GetPosition());
		break;
	}
	return true;
}

bool SpinEvent::SetProperty(PrivSpinEvent *p,
                                  JSContext *cx, 
                                  JSObject *obj, 
                                  int id, 
                                  JS::MutableHandle<JS::Value>& vp)
{
	wxSpinEvent *event = (wxSpinEvent*) p->GetEvent();

	switch ( id )
	{
	case P_POSITION:
		{
			int pos;
			if ( FromJS(cx, vp, pos) )
				event->SetPosition(pos);
			break;
		}
	}
	return true;
}

	
WXJS_BEGIN_GET_SET_STR_PROP(PrivSpinEvent, SpinEvent)
	NotifyEvent::SetStringProperty((PrivNotifyEvent*)p, cx,  obj, propertyName, vp);
	return true;
ZZZJS_END_GET_SET_STR_PROP